#!/bin/sh
source ./.aosbuild

aos_compiler ${CC:-clang}
aos_cflags -march=native -std=c99 -Os -pipe -Wall -Wextra -Werror -pedantic
aos_lflags $CFLAGS

UTILS=( echo true false sleep cat yes printenv basename dirname head sync \
	logname uname )
NEEDADDON=( 1 0 0 0 1 1 0 0 0 1 0 0 1 )
i=0
for f in "${UTILS[@]}"
 do
  aos_bin bin/${f}
  aos_src src/${f}.c
  [ ${NEEDADDON[i]} -ne 0 ] && aos_addsrc src/helpers.c
  i=$(($i+1))
  aos_main ${@}
 done
